### ISSUE TITLE
[feature idea] Add "status" command

### ISSUE THREAD

**Issue by TonyVlcek** [n4n0GH/ulauncher_clockify#1]
First of all, thank you very much for this extensions. Since I installed it I'm using it on daily basis and it's become the primary way for me to interact with the clockify tool, I rarely ever have to jump back to the Web UI.

The `clock status`  command that I propose would show a notification displaying the name and the current time tracked by the currently running time-entry. If there is no currently running tracking the notification would reflect that as well.

Alternative: Instead of a notification this info could show up directly in the options listing in the Ulauncher, I think that both can work well.

---

💡 The `/time-entries` [endpoint](https://clockify.me/developers-api) has  a bool `in-progress` parameter which should allow the retrieval of this currently running time entry.

**Comment by n4n0GH** [comment]
Good addition! Thanks for the PR :)
