### ISSUE TITLE
Extension crashes due to failing to find dateutil

### ISSUE THREAD

**Issue by hpr1999** [n4n0GH/ulauncher_clockify#5]
Hey there, I'd like to use this extension, but the extension crashes on startup.
Ulauncher says it crashed since it could not import the `dateutil` module.
I've tried to install it manually using pip and have found that I can only install `python-dateutil`.

Do you have an idea how this could be fixed?

**Comment by n4n0GH** [comment]
`python-dateutil` is exactly what you need. Please give that a try.

**Comment by hpr1999** [comment]
Sorry, should've specified further - I installed that, but that did not change the behaviour.
I have just tried installing again and have come up with the same results.
I've attached to Screenshots of the situation:
![image](https://user-images.githubusercontent.com/26067274/106650600-62f8c300-6593-11eb-865f-00173d7523f8.png)
![image](https://user-images.githubusercontent.com/26067274/106650763-950a2500-6593-11eb-91cd-bfc6ccf6d94a.png)
![image](https://user-images.githubusercontent.com/26067274/106650625-69873a80-6593-11eb-83f9-074702434fbc.png)

(For completeness' sake: I've also tried it with the `--user`-flag, which does not change anything)

**Comment by n4n0GH** [comment]
What happens if you open up a python session and type `from dateutil.parser import parse`. It should fail, as does the ulauncher extension, but it shouldn't because you have it installed already.

**Comment by hpr1999** [comment]
Hi, I'm sorry for not answering for such a long time.
After not using the machine for a long time, I was now able to locate the problem.
The root of the problem was as follows: 
```
$ pip3 -V
pip 21.0 from /home/hpr/.local/lib/python3.7/site-packages/pip (python 3.7)
 $ python3 -V
Python 3.6.9
```
I instead had to install the missing packages `python-dateutil` and `datetime` with `python3 -m pip install <package>`

Now that's resolved, the plugin no longer crashes. Thank you for your time!

**Comment by hpr1999** [comment]
Since I no longer have a problem, I'll take the freedom to close this.

**Comment by n4n0GH** [comment]
nice, glad you were able to solve this issue.
